import "./globals.css";
import { Analytics } from "@vercel/analytics/next"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const googleAnalyticsId = process.env.NEXT_PUBLIC_GOOGLE_LINK;
const Tag = process.env.NEXT_PUBLIC_TAG;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-NTXQZNP44V"></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-NTXQZNP44V');
            `,
          }}
        />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet" />
      </head>
      <body className="antialiased" style={{ fontFamily: "'Inter', 'Roboto', 'Helvetica Neue', Arial, 'sans-serif'" }}>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
